### ISSUE TITLE
Binary Release

### ISSUE THREAD

**Issue by bitzl** [go-amigo/namesgen#1]
I'd like to use namesgen in several projects where it would be the easiest to download a binary directly to the server (or while building a Docker image) instead of compiling from source.

Could you please create a release and add a binary? If you don't have the time to do so I'd be happy to help out.

**Comment by ambakshi** [comment]
Thanks for the suggestion. I didn't know how to create a binary release until now. I've put up a linux  and osx version (compiled with go 1.6.3).

**Comment by bitzl** [comment]
Thank's, great :-)

There's a typo in the Download-Link. This would work:

```
curl -sSL https://github.com/go-amigo/namesgen/releases/download/v1.0/namesgen_$(uname -s)-$(uname -m) > /usr/local/bin/namesgen
chmod +x /usr/local/bin/namesgen
```

**Comment by ambakshi** [comment]
Fixed, thank you! :)
